### ISSUE TITLE
Security Data Issues SQL Password in clear text

### ISSUE THREAD

**Issue by shaybenb** [Red-Folder/red-folder.com#14]
Hi ,

url : https://github.com/Red-Folder/red-folder.com/blob/28da08f12c4f65c641b364a75899bb1d2df79120/src/Red-Folder.com/Properties/PublishProfiles/publish-module.psm1
file : src/Red-Folder.com/Properties/PublishProfiles/publish-module.psm1

has commit that need to remove from the github history
attacker can see it old changes and use them to access to your SQL DB.

you enable to be access from your netowrk only 👍 , But still change the password.

![image](https://user-images.githubusercontent.com/46863888/103547015-80f7d880-4eac-11eb-8d4c-6b688312e2ef.png)
![image](https://user-images.githubusercontent.com/46863888/103547039-89501380-4eac-11eb-8729-39ac8c0a3587.png)

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by Red-Folder** [comment]
Thanks you @shaybenb for taking the time to log this.

If you look at the file in question the line you have picked up is a Microsoft provided example and is not a real connection.  The password in question is also just a placeholder.

(Thus not a problem)

**Comment by shaybenb** [comment]
you are rihgt , sorry for that....
